// <auto-generated />
using System;
using Balogh_David_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaloghDavidProject.Migrations
{
    [DbContext(typeof(LaptopContext))]
    [Migration("20230114181750_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Balogh_David_Project.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("Balogh_David_Project.Models.DistributedLaptop", b =>
                {
                    b.Property<int>("LaptopID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DistributorID")
                        .HasColumnType("INTEGER");

                    b.HasKey("LaptopID", "DistributorID");

                    b.HasIndex("DistributorID");

                    b.ToTable("DistributedLaptop", (string)null);
                });

            modelBuilder.Entity("Balogh_David_Project.Models.Distributor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("TEXT");

                    b.Property<string>("DistributorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Distributor", (string)null);
                });

            modelBuilder.Entity("Balogh_David_Project.Models.Laptop", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManufacturerID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ManufacturerID");

                    b.ToTable("Laptop", (string)null);
                });

            modelBuilder.Entity("Balogh_David_Project.Models.Manufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Manufacturer", (string)null);
                });

            modelBuilder.Entity("Balogh_David_Project.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LaptopID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("LaptopID");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("Balogh_David_Project.Models.DistributedLaptop", b =>
                {
                    b.HasOne("Balogh_David_Project.Models.Distributor", "Distributor")
                        .WithMany("DistributedLaptops")
                        .HasForeignKey("DistributorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Balogh_David_Project.Models.Laptop", "Laptop")
                        .WithMany("DistributedLaptops")
                        .HasForeignKey("LaptopID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distributor");

                    b.Navigation("Laptop");
                });

            modelBuilder.Entity("Balogh_David_Project.Models.Laptop", b =>
                {
                    b.HasOne("Balogh_David_Project.Models.Manufacturer", "Manufacturer")
                        .WithMany("Laptops")
                        .HasForeignKey("ManufacturerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Balogh_David_Project.Models.Order", b =>
                {
                    b.HasOne("Balogh_David_Project.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Balogh_David_Project.Models.Laptop", "Laptop")
                        .WithMany("Orders")
                        .HasForeignKey("LaptopID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Laptop");
                });

            modelBuilder.Entity("Balogh_David_Project.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Balogh_David_Project.Models.Distributor", b =>
                {
                    b.Navigation("DistributedLaptops");
                });

            modelBuilder.Entity("Balogh_David_Project.Models.Laptop", b =>
                {
                    b.Navigation("DistributedLaptops");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Balogh_David_Project.Models.Manufacturer", b =>
                {
                    b.Navigation("Laptops");
                });
#pragma warning restore 612, 618
        }
    }
}
